spring.config.import=file:${LOCAL_ENV_FILE:./.env}[.properties]

server.port=${OCPP_WSS_PORT}
server.address=127.0.0.1
server.ssl.enabled=true
server.ssl.key-store=${OCPP_WSS_KEY_STORE}
server.ssl.key-store-password=${OCPP_WSS_KEY_STORE_PASSWORD}
server.ssl.key-store-type=${OCPP_WSS_KEY_STORE_TYPE:PKCS12}

ocpp.ingress.enabled=true
ocpp.station.charging-station-id=${OCPP_CHARGING_STATION_ID}
ocpp.station.station-id=${OCPP_STATION_ID}
ocpp.station.allowed-evse-ids=${OCPP_ALLOWED_EVSE_IDS}
ocpp.station.password=${OCPP_STATION_PASSWORD}
ocpp.kafka-topic=charging.transaction.observed.v1

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAPSERVERS}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties[enable.idempotence]=true
spring.kafka.producer.properties[max.request.size]=1048576
