#!/usr/bin/env python3
"""Create ignored, local-only TLS material and add its settings to the existing .env."""
import os
from pathlib import Path
import secrets
import subprocess


def main():
    root = Path(__file__).resolve().parent.parent
    env_file = root / ".env"
    if not env_file.is_file():
        raise SystemExit("Create .env from .env.example and set DB passwords first.")
    java_home = os.environ.get("JAVA_HOME")
    if not java_home:
        raise SystemExit("Set JAVA_HOME to your Java 21 installation.")
    keytool = str(Path(java_home) / "bin" / "keytool")
    directory = root / "secrets"
    targets = [directory / name for name in (
        "telemetry-worker.p12", "telemetry-worker.crt", "telemetry-client-trust.p12")]
    if any(path.exists() for path in targets):
        raise SystemExit("TLS material already exists; existing keys and .env were preserved.")

    os.umask(0o077)
    directory.mkdir(mode=0o700, exist_ok=True)
    password = secrets.token_hex(24)
    process_env = dict(os.environ, EVC_TLS_PASSWORD=password)

    def run(*arguments):
        subprocess.run([keytool, *arguments], env=process_env, check=True,
                       stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)

    try:
        run("-genkeypair", "-alias", "telemetry-worker", "-keyalg", "RSA", "-keysize", "2048",
            "-sigalg", "SHA256withRSA", "-dname", "CN=localhost", "-ext", "SAN=dns:localhost,ip:127.0.0.1",
            "-validity", "30", "-storetype", "PKCS12", "-keystore", str(targets[0]),
            "-storepass:env", "EVC_TLS_PASSWORD", "-keypass:env", "EVC_TLS_PASSWORD")
        run("-exportcert", "-rfc", "-alias", "telemetry-worker", "-keystore", str(targets[0]),
            "-storepass:env", "EVC_TLS_PASSWORD", "-file", str(targets[1]))
        run("-importcert", "-noprompt", "-alias", "telemetry-worker", "-storetype", "PKCS12",
            "-keystore", str(targets[2]), "-storepass:env", "EVC_TLS_PASSWORD", "-file", str(targets[1]))
    except subprocess.CalledProcessError:
        for path in targets:
            path.unlink(missing_ok=True)
        raise SystemExit("Local TLS generation failed; .env was preserved.") from None

    settings = {
        "TELEMETRY_HTTPS_PORT": "18443",
        "TELEMETRY_TLS_KEY_STORE": "file:./secrets/telemetry-worker.p12",
        "TELEMETRY_TLS_KEY_STORE_PASSWORD": password,
        "TELEMETRY_TLS_TRUST_STORE": "./secrets/telemetry-client-trust.p12",
        "TELEMETRY_TLS_TRUST_STORE_PASSWORD": password,
    }
    original = env_file.read_text()
    lines = []
    for line in original.splitlines(keepends=True):
        name = line.split("=", 1)[0]
        if name in settings:
            # Keep an already selected local port.
            if name == "TELEMETRY_HTTPS_PORT":
                settings[name] = line.split("=", 1)[1].strip()
        else:
            lines.append(line)
    updated = "".join(lines).rstrip("\n") + "\n\n# Local-only TLS, generated by create-local-telemetry-tls.py\n"
    updated += "".join(f"{name}={value}\n" for name, value in settings.items())
    temporary = root / ".env.tls-tmp"
    temporary.write_text(updated)
    temporary.chmod(0o600)
    temporary.replace(env_file)
    print("Local TLS created in secrets/; .env updated (0600). Certificate expires in 30 days.")


if __name__ == "__main__":
    main()
